Add custom url category resource
jeremmfr/terraform-provider-junos pull request #109
Opened 2021-02-05 08:22 UTC by a-d-v

2021-02-05 12:33 UTC, jeremmfr requested changes
Thanks for the work, there are some mistakes to correct

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category.go
> +				confRead.value = append(confRead.value, strings.Trim(strings.TrimPrefix(itemTrim, "value "), "\""))
Trim `"` character isn't necessary
```suggestion
				confRead.value = append(confRead.value, strings.TrimPrefix(itemTrim, "value "))
```

2021-02-05 12:33 UTC, jeremmfr commented on website/docs/r/security_utm_custom_url_category.html.markdown
> +$ terraform import junos_security_utm_custom_url_category.demo_url_category new_category
use `name` in example for `id` in import example
```suggestion
$ terraform import junos_security_utm_custom_url_category.demo_url_category custom-category
```

2021-02-05 12:33 UTC, jeremmfr commented on website/junos.erb
> +          <a href="/docs/providers/junos/r/security_utm_custom_url_category.html">junos_security_utm_custom_url_category</a>
link not aligned with others
```suggestion
            <a href="/docs/providers/junos/r/security_utm_custom_url_category.html">junos_security_utm_custom_url_category</a>
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category.go
> +		)
Compact to 2 lines
```suggestion
		return diag.FromErr(fmt.Errorf(
			"security utm custom-objects custom-url-category %v already exists", d.Get("name").(string)))
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category_test.go
> +							"value.#", "new-category"),
Testacc fail
```suggestion
							"value.#", "1"),
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category_test.go
> +							"value.#", "new-category2"),
Testacc fail
```suggestion
							"value.#", "2"),
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category_test.go
> +}
Testacc fail, custom-pattern1 doesn't exist
```suggestion
resource junos_security_utm_custom_url_pattern "testacc_URLCategory1" {
  name  = "custom-pattern1"
  value = ["*.google.com"]
}
resource junos_security_utm_custom_url_category "testacc_URLCategory" {
  name = "testacc_URLCategory"
  value = [
    junos_security_utm_custom_url_pattern.testacc_URLCategory1.name,
  ]
}
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category_test.go
> +  value = ["custom-pattern1", "custom-pattern2"]
Testacc fail, custom-pattern1 and custom-pattern2 doesn't exist
```suggestion
resource junos_security_utm_custom_url_pattern "testacc_URLCategory1" {
  name  = "custom-pattern1"
  value = ["*.google.com"]
}
resource junos_security_utm_custom_url_pattern "testacc_URLCategory2" {
  name  = "custom-pattern2"
  value = ["*.google.fr"]
}
resource junos_security_utm_custom_url_category "testacc_URLCategory" {
  name = "testacc_URLCategory"
  value = [
    junos_security_utm_custom_url_pattern.testacc_URLCategory1.name,
    junos_security_utm_custom_url_pattern.testacc_URLCategory2.name,
  ]
```

2021-02-05 12:33 UTC, jeremmfr commented on junos/resource_security_utm_custom_url_category.go
> +		)
Compact to 2 lines
```suggestion
		return nil, fmt.Errorf(
			"missing security utm custom-objects custom-url-category with id '%v' (id must be <name>)", d.Id())
```

2021-02-05 14:34 UTC, a-d-v commented
@jeremmfr  Still learning, thank you for your good review

2021-02-06 13:31 UTC, jeremmfr approved these changes

2021-02-06 13:32 UTC, merged