Add security_address_book resource
jeremmfr/terraform-provider-junos pull request #146
Opened 2021-03-15 22:35 UTC by tagur87

* Add `junos_security_address_book` resource (Fixes #137)
* Fix missing `security_screen` documentation in website sidebar.

2021-03-15 22:40 UTC, tagur87 commented
@jeremmfr - I have completed work on this resource. Just a quick note on some of the ways I completed this resource's logic. 

Instead of the original way I proposed with having one `address` block, I decided to use different types of blocks for the different types of address types.

The reason I chose this was two fold...
1) Simplifies the logic and work to add the data back to the proper `[]map[string]interface{}`

2) Allows for the potentials of using TF [Dynamic Blocks](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) to do address objects based on var lists or other data sources. 

Let me know if you have any specific reasons why this method will not work.

Also, side note...I also found some missing resources from the side bar of the website, so I added those in.

Thanks for reviewing!

JT

2021-03-16 09:03 UTC, jeremmfr requested changes
Great job. There is a minor changes that must be addressed.

Thanks for missing links in sidebar, I will add a Actions to avoid forgetting it again ;)

2021-03-16 09:03 UTC, jeremmfr commented on junos/func_common.go
> +	ip := net.ParseIP(wildcardSplit[1]).To4()
Need to be first element
```suggestion
	ip := net.ParseIP(wildcardSplit[0]).To4()
```

2021-03-16 09:03 UTC, jeremmfr commented on junos/resource_security_address_book.go
> +				ForceNew: true, // Not sure if this is right?
Remove comment, ForceNew must be present
```suggestion
				ForceNew: true,
```

2021-03-16 09:03 UTC, jeremmfr commented on junos/resource_security_address_book.go
> +		d.SetId("")
Check if the name is present in struct (not empty result when show configuration).
If you create a address-book only with `description`, provider produce inconsistent result after apply.
```suggestion
	if addressOptions.name == "" {
		d.SetId("")
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +  * `description` - (Required)(`String`) Description of network address.
Description is optional
```suggestion
  * `description` - (Optional)(`String`) Description of network address.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +  * `description` - (Required)(`String`) Description of network address.
Description is optional
```suggestion
  * `description` - (Optional)(`String`) Description of wildcard address.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +  * `description` - (Required)(`String`) Description of dns name address.
Description is optional
```suggestion
  * `description` - (Optional)(`String`) Description of dns name address.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +  * `description` - (Required)(`String`) Description of range address.
Description is optional
```suggestion
  * `description` - (Optional)(`String`) Description of range address.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +  * `description` - (Required)(`String`) Description of address-set.
Description is optional
```suggestion
  * `description` - (Optional)(`String`) Description of address-set.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +Junos security zone can be imported using an id made up of `<name>`, e.g.
```suggestion
Junos security address book can be imported using an id made up of `<name>`, e.g.
```

2021-03-16 09:03 UTC, jeremmfr commented on website/docs/r/security_address_book.html.markdown
> +# junos_security_zone
```suggestion
# junos_security_address_book
```

2021-03-16 12:06 UTC, tagur87 commented
Thanks for the feedback! I updated all these in the latest commit.

2021-03-17 08:10 UTC, jeremmfr requested changes
After tests, I noticed that we can attach several zones on address-book. `attach_zone` should be a list.

2021-03-17 12:19 UTC, tagur87 commented
> After tests, I noticed that we can attach several zones on address-book. `attach_zone` should be a list.

Good catch! Thanks! I'll get that fixed here shortly

2021-03-17 14:46 UTC, jeremmfr approved these changes

2021-03-17 14:46 UTC, merged