Fixes #171: Added pool_utilization thresholds to nat source pools
jeremmfr/terraform-provider-junos pull request #172
Opened 2021-04-09 13:39 UTC by edpio19

* add `pool-utilization-alarm` argument to `security_nat_source_pool` resource

2021-04-12 08:48 UTC, jeremmfr requested changes
A nested block `pool_utilization_alarm` just for 2 arguments is a bit too complex.
Can you rework the PR to propose only 2 new arguments ? : 
* `pool_utilization_alarm_raise_threshold`
* `pool_utilization_alarm_clear_threshold`

2021-04-16 09:07 UTC, edpio19 commented
@jeremmfr Changes have been made. Thank you for reviewing!

2021-04-16 15:27 UTC, jeremmfr commented
> @jeremmfr Changes have been made. Thank you for reviewing!
The PR displays the commits already merged. Can you rebase correctly from main or recreate a new PR ?

2021-04-19 06:41 UTC, edpio19 commented
Thank you for pointing this out. It has been fixed now.

2021-04-19 09:23 UTC, jeremmfr requested changes
There are reordering to do and a `RequiredWith` option to add to clear-threshold argument

2021-04-19 09:23 UTC, jeremmfr commented on junos/resource_security_nat_source_pool.go
> +	poolUtilizationAlarmClearThreshold int
Can you insert the new options to respect type then alphabetical order ?
```suggestion
	portNoTranslation                  bool
	poolUtilizationAlarmClearThreshold int
	poolUtilizationAlarmRaiseThreshold int
	portOverloadingFactor              int
	name                               string
	portRange                          string
	routingInstance                    string
	address                            []string
```

2021-04-19 09:23 UTC, jeremmfr commented on junos/resource_security_nat_source_pool.go
> +	}
Can you insert the new options to respect resource (alphabetical) order ?

2021-04-19 09:23 UTC, jeremmfr commented on junos/resource_security_nat_source_pool.go
> +				}
Can you insert the new options to respect resource (alphabetical) order ?

2021-04-19 09:23 UTC, jeremmfr commented on junos/resource_security_nat_source_pool.go
> +	}
Can you insert the new options to respect resource (alphabetical) order ?

2021-04-19 09:23 UTC, jeremmfr commented on website/docs/r/security_nat_source_pool.html.markdown
> +* `pool_utilization_alarm_clear_threshold` - (Optional)(`Int`) Lower threshold at which an SNMP trap is triggered. Range 40 through 100.
Can you insert the new options to respect resource (alphabetical) order ?

2021-04-19 09:23 UTC, jeremmfr commented on junos/resource_security_nat_source_pool.go
> +			},
Can you insert the new options to respect optional then alphabetical order ?
The `raise-threshold` is required with `clear-threshold` :
```suggestion
			"pool_utilization_alarm_raise_threshold": {
				Type:         schema.TypeInt,
				Optional:     true,
				ValidateFunc: validation.IntBetween(50, 100),
			},
			"pool_utilization_alarm_clear_threshold": {
				Type:         schema.TypeInt,
				Optional:     true,
				RequiredWith: []string{"pool_utilization_alarm_raise_threshold"},
				ValidateFunc: validation.IntBetween(40, 100),
			},
```

2021-04-19 13:38 UTC, jeremmfr approved these changes

2021-04-19 13:38 UTC, jeremmfr commented
Looks good to me

2021-04-19 13:42 UTC, merged