Add no_multicast_echo and default_address_selection system options
jeremmfr/terraform-provider-junos pull request #96
Opened 2021-01-25 18:36 UTC by a-d-v

2021-01-26 13:48 UTC, jeremmfr requested changes
It would have been nice to create an issue before.
Can you correct the order and testacc errors?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system.go
> +	defaultAddressSelection              bool
Can you respect the alphabetical order in booleans ?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system.go
> +			},
Can you respect the alphabetical order in arguments ?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system.go
> +	}
Can you respect the alphabetical order in arguments ?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system.go
> +				confRead.defaultAddressSelection = true
Can you respect the alphabetical order in arguments ?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system.go
> +	}
Can you respect the alphabetical order in arguments ?

2021-01-26 13:48 UTC, jeremmfr commented on website/docs/r/system.html.markdown
> +* `default_address_selection` - (Optional)(`Bool`) Use loopback interface as source address for locally generated packets.
Can you respect the alphabetical order in arguments ?

2021-01-26 13:48 UTC, jeremmfr commented on junos/resource_system_test.go
> +							"default_address_selection", "true"),
testacc fails : the 2 arguments is missing in return of testAccJunosSystemConfigCreate() function

2021-01-26 20:24 UTC, a-d-v commented
thank you for the good suggestions! Pull request updated

2021-01-27 08:59 UTC, jeremmfr requested changes
Testacc fail: junos parameters missing in function delSystem() so removing the parameters doesn't work.
There is also still a small alphabetical order error

2021-01-27 08:59 UTC, jeremmfr commented on junos/resource_system.go
> +			"default_address_selection": {
Need to be before `domain_name` to respect alphabetical order.

2021-01-27 16:55 UTC, jeremmfr approved these changes
it looks good to me

2021-01-27 16:55 UTC, merged